### ISSUE TITLE
Are there any public examples other than mruby?

### ISSUE THREAD

**Issue by mmxsrup** [RUB-SysSec/aurora#12]
Hi, This project is really great!

I want to run aurora using examples other than mruby. Can I access the scripts to build the targets used in the paper evaluation? Or do I have to reproduce the environment myself?

It would be helpful if you could share steps or scripts to reproduce other examples. Thank you in advance for your time.

**Comment by mu00d8** [comment]
Hi,

I'm afraid, but there's no automated building scripts for all the bugs. If I ever have time, I might be able to build them but my todo stack is large. PRs welcome if you want to do this
