### ISSUE TITLE
aurora for python not working

### ISSUE THREAD

**Issue by HangShuLYH** [RUB-SysSec/aurora#14]
When I use aurora for python(bug 17, bug 9 in the Paper), I find that the root cause seems undiscovered by the pintool.
For example, in the bug 9, the root cause is in the function "getdata" of /Mouldes/zipimport.c", but none of the instructions in "getdata" is recorded by the pintool. 
When I use gdb to debug the bug, I set breakpoint at "getdata", gdb prints using host libthread_db library "lib/x86_64-linux-gnu/libthread_db.so.1".
So It seems that the get_data function is not recorded in the trace.

**Comment by mu00d8** [comment]
The tracer is configured to only trace instructions in the main executable, not libraries. 

Remove the `&& IMG_IsMainExecutable(image)` if you want to trace libraries (be aware this will significantly increase trace sizes)
https://github.com/RUB-SysSec/aurora/blob/707b94f1d7ac46c9e4575dfcbbf0dab08bbb3af2/tracing/aurora_tracer.cpp#L284
