### ISSUE TITLE
Question: Are the running times in Table 5 of the paper obtained running on a single core or on 32?

### ISSUE THREAD

**Issue by chq-matteo** [RUB-SysSec/aurora#5]
Hello, thank you for releasing this tool.

I was reading the [usenix paper](https://www.usenix.org/system/files/sec20-blazytko.pdf) and saw the table 5 with a summary of time spent on each phase of the pipeline, but I could not determine if these times are measured as wall clock time using all 32 cores of the machine or cpu time.

![image](https://user-images.githubusercontent.com/6654800/131977858-11a3dc0d-8f99-41c5-af2d-76e5326ec8e5.png)

I have also a similar question about the fuzzing time for each target, are the time values in the paper measured as cpu time or wall clock time for 32 cores?

Thank you

**Comment by mu00d8** [comment]
Hi,
thanks for your interest in our work!
All times have been measured as wall clock time. Tracing and root cause analysis used all 32 cores, however, the fuzzer was run only on a single core.
